# 继承 Rails 官方推荐的规范
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 3.3.8

# 1. 允许双引号 (Rails 生成器默认使用双引号，没必要强行改单引号)
Style/StringLiterals:
  EnforcedStyle: double_quotes

# 2. 适当放宽行长度限制 (现代显示器 80 字符太短了，120 比较合理)
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'

# 3. 禁用强制文档注释 (不需要每个 Class 都写 magic comment，浪费时间)
Style/Documentation:
  Enabled: false

# 4. 允许在逻辑清晰的情况下使用多行三元运算符
Style/MultilineTernaryOperator:
  Enabled: false

# 5. 针对 Rails 路由文件的特殊优化 (允许其块定义较长)
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

# 6. 禁用空方法体告警 (Rails 经常有空的 controller action)
Style/EmptyMethod:
  Enabled: false

# 7. 忽略某些自动生成的安全性警告 (由你自己把控)
Bundler/GemComment:
  Enabled: false